name: Build App, Unit Test, UI Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-unit_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install app dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Show my SoftUni username
      run: echo "ValeriDimov84"


  ui_test:
    needs: build-unit_test 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install app dependencies
      run: npm install
    - name: Start app on localhost and close the open terminal
      run: npm start &
    - name: Install Playwright
      run: npx playwright install
    - name: Run ui tests
      run: npm run test:ui

  deploy:
    needs: ui_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Deploy app on render.com
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_SERVER_KEY }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        clear_cache: true
        wait_deploy: true